services:
  mongodb:
    image: mongo:latest
    container_name: agro_mongo_dev
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=agroadmin
      - MONGO_INITDB_ROOT_PASSWORD=agro123
    env_file:
      - ./infrastructure/envs/.env.dev
    networks:
      - dev-net
  backend1:
    build: ./backend
    container_name: agro_backend1_dev
    env_file:
      - ./infrastructure/envs/.env.dev
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  backend2:
    build: ./backend
    container_name: agro_backend2_dev
    env_file:
      - ./infrastructure/envs/.env.dev
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  frontend:
    build: ./frontend
    container_name: agro_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend1
      - backend2
    command: ["npm", "run", "dev"]
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/logs/nginx:/var/log/nginx
    networks:
      - dev-net
    depends_on:
      - frontend
      - backend1
      - backend2
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infrastructure/monitoring/loki-config.yaml:/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./infrastructure/monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log:ro
      - ./infrastructure/logs/nginx:/logs/nginx:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

volumes:
  data:
  logs:
networks:
  dev-net:
    driver: bridge
