services:
  mongodb:
    image: mongo:latest
    container_name: agro_mongo_dev
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=agroadmin
      - MONGO_INITDB_ROOT_PASSWORD=agro123
    env_file:
      - ./build/.env.dev
    networks:
      - dev-net
  backend1:
    build: ./backend
    container_name: agro_backend1_dev
    environment:
      - BACKEND_PORT_NUMBER=5001
    env_file:
      - ./build/.env.dev
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  backend2:
    build: ./backend
    container_name: agro_backend2_dev
    environment:
      - BACKEND_PORT_NUMBER=5002
    env_file:
      - ./build/.env.dev
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  frontend:
    build: ./frontend
    container_name: agro_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend1
      - backend2
    command: ["npm", "run", "dev"]
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./build/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - dev-net
    depends_on:
      - frontend
      - backend1
      - backend2
volumes:
  data:
  logs:
networks:
  dev-net:
    driver: bridge
